BBBB BBBBBBBBBB
XXXXXXXXX XXXXXXXXXXXXX XXXXXXX XX
    BB BBBBBBBBBBBBBXXXXXXXXXBBBBB
    BB BBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFXXXXXX
    BBBBB
    BBB BBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBB XXXXXXBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBB XXXXXXBBBBBBBB BBBBB BB BBBBBB BBBBBBBBBBBBBBBB XXXXXXBBBBBBBBBBBXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBB BBBBB BB BBBB
                XXXXBB BBB BBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBB XXXXXXBBBBBBB BBB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBB XXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBB XXXXXXBBBBBXBBBB BBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXBBBBBX
                    BB BBB BBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBB
                    BB BBBBBBBBBBBBBBBBB
                        
                    BBBB
                        
                        BB BBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBB
                            FFFFFFFFF
                        BBBBB
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXFFFFXXXXXX
                    BBBBB
                XXXXXX
            BBBBBB
        XXXXXX
    BBBBBB

XXXXXXXXXXX

XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX


    XXX
 X XXXXXXX XX XXXX XX XXXXXXXXXXX
 XX
XXX XXXXXXXXXXXX X X
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXX X
        XX XXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXXXXXXX X XXX
        XXX XX X XXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXX XX XX XXXXXXXXX X
            XX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXXXX
            X
        X XXXX XX XXXXXXX XX XX XXXXXXXX XX XX XX XXXXX X
            XXXXXXXXXXXXXXXXXX X XXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
        XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    XXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX X
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXXXX XXXXXX XXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    XXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXX XXXX XXXXXXX
    XX
    XXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXXXXXXXX XXXX
    XX
    XXXXXXXXXXXXXXX XX X
        XX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XX
    XXXXXXXXXXXXXXX XX X
        XX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X
        XXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXX XX
            X
        X
    XX
    XXXXXXXXXXXXXXXXXXXXX XXX X
        XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
    XX
    XXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXX X XXXXX
        XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXX X XXXXXX
            XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
        XX XXXXXXXXXX XX XXXXXXXXXXXXXXXXX X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX XX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XX
    XXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X
        XXXXXXXXXXXXXXXXXXX
        XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXX X XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
        XX XXXXXX X XX X XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
        X XXXX X XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
        X
    XX
    XXXXXXXXXXXXXXXXXXXX XXXXX X
        XXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXXXXXXXXX X
            XX XXXXXXXXXXXXX XX XX X
                XXXX X XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
                XXXX X XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            X
            XXXXXX XXXXXX
        X
        XXXXXXXX XXXXXXXXXXX X
            XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXX X XXXX X XXXXXXXXXXX X XX X XXXXX
                XXXXXX XXXXXXXXXXXXXX X XXXX X XXXXXXXXXXXX X XX X XXXX
            XXX
            XXXXXX XXXXXX
        X
        XXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        X
    X
XX


    XXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXX X X XX X X XXXXXXXXXXXXXXXXXXXXXX XXXX X
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXX XXXXXXXXXX X XXXXXXX XXXXXX
        XXX XXXX X X XX X XXXXXXXXXXXXXXXXXX X XXXX X
            
            
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX X
            X
                
                XXX XXXX X XXXXXXXXXXXXXXXXXXXXXX
                
                XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXX X XXXX X XXXXXXXXXXX
            X
        X
    X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX


XXXXXXXXX


XXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXX X
        XXXXXX XXXX
    X
XXXXXXXX