BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXBBBBBBBB
BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX  gettext(u'Password reset') 
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXXBBBBBBBB
BBBBB BBBBBBB

XXX gettext(u"Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.") XXXX

XXXXX XXXXXXXXXXXXXXBBBBBBBBBB
XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        
        XXXXXX XXXXXXXXXXXXXXX gettext(u'Email address:') XXXXXXXX
        
    XXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Reset my password') XX
XXXXXXXXXXX
XXXXXXX

BBBBBBBB
