BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXBBBBBBBB
BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX  gettext(u'Password reset confirmation') 
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXXBBBBBBBB
BBBBB BBBBBBB

BB BBBBBBBBB

XXX gettext(u'Please enter your new password twice so we can verify you typed it in correctly.') XXXX

XXXXX XXXXXXXXXXXXXXBBBBBBBBBB
XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'New password:') XXXXXXXX
        
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Confirm password:') XXXXXXXX
        
    XXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Change my password') XX
XXXXXXXXXXX
XXXXXXX

BBBB

XXX gettext(u'The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.') XXXX

BBBBB

BBBBBBBB
