BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB BBBBBBBB
    XX XXXXXXXX gettext(u'Documentation') XXXX X BBBBB gettext(u'Change password')  X
    XX XXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'Log out') XXXXBBBBBBBB
BBBBB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
        XXXXXXXX  gettext(u'Password change') 
    XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXXBBBBBBBB
BBBBB BBBBBBB
    XXX gettext(u'Your password was changed.') XXXX
    XXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXX
        X
    XXXXXXXX
BBBBBBBB
