BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX  gettext(u'Password reset') 
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB

XXX gettext(u'Your password has been set.  You may go ahead and log in now.') XXXX

XXXXX XXXXXXXX gettext(u'Log in') XXXXXXXX

BBBBBBBB
