"""
Django settings for fy_rabc project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z#73gg6w^fmwegcz*eods_)ciq94o=&f*6-8k_+*)2p!)ir1&*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',  # 令牌认证
    'fy_rabc_sys'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'fy_rabc.MiddlewarePermission.MiddlewarePermission',
]

ROOT_URLCONF = 'fy_rabc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fy_rabc.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'fy_rabc',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': 'root',
        'OPTIONS': {
            'init_command': 'SET sql_mode="STRICT_TRANS_TABLES"',
            'charset': 'utf8mb4',
            # "init_command": "SET foreign_key_checks=0",
        }

    },
    'sqlite3': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------simpleui 配置开始-------------------------------------

# 首页配置
# SIMPLEUI_HOME_PAGE = 'https://baidu.com'

# 设置simpleui 点击首页图标跳转的地址
SIMPLEUI_INDEX = '/admin'

# 首页标题
SIMPLEUI_HOME_TITLE = 'CRM'

# 自定义SIMPLEUI的Logo
SIMPLEUI_LOGO = '../../static/img/fyhq.png'

# 自定义ICON
CUSTOM_ICON = '../../static/img/fy.ico'

# 服务器信息
SIMPLEUI_HOME_INFO = False

# 快速操作
SIMPLEUI_HOME_QUICK = True

# 最近动作
SIMPLEUI_HOME_ACTION = False

# 使用分析
SIMPLEUI_ANALYSIS = False

# 离线模式
SIMPLEUI_STATIC_OFFLINE = True

# 关闭Loading遮罩层
SIMPLEUI_LOADING = False

# 添加自定义菜单
SIMPLEUI_CONFIG = {
    'system_keep': True,
    # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    # 'menu_display': ['Simpleui', '测试', '权限认证', '动态菜单测试'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'dynamic': False,
    'menus': [{
        'name': '动态菜单测试',
        'icon': 'fa fa-desktop',
        'models': [{
            'name': '测试',
            'url': '../../sys/org',
            'icon': 'far fa-surprise'
        }]
    }]
}

# 菜单默认图标开启/关闭（True:开启默认图标，默认为True.False:关闭默认图标）
SIMPLEUI_DEFAULT_ICON = True

# 指定修改菜单图标
SIMPLEUI_ICON = {
    # '机器人信息表': 'fab fa-apple',
    # '槽位填充信息表': 'fas fa-user-tie',
}

# 最大打开页签数
MAX_OPEN_PAGES = 10

# --------------------------simpleui 配置结束-------------------------------------

# 白名单
WHITE_URL_LIST = [
    r'^/admin/.*',  # 放行admin应用url
    r'^/sys/register/',
    r'^/sys/get_auth_img/',
    r'^/login/',
    r'^/sys/comm_']

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# 设置中文
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# 时区
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'fy_rabc_sys/static'),
)
STATIC_ROOT = os.path.join(BASE_DIR, '/var/rabc')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORD = {
    # 权限认证
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # IsAuthenticated 仅通过认证的用户
        'rest_framework.permissions.AllowAny',  # AllowAny 允许所有用户
        'rest_framework.permissions.IsAdminUser',  # IsAdminUser 仅管理员用户
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # IsAuthenticatedOrReadOnly 认证的用户可以完全操作，否则只能get读取
    ),
    # 身份认证
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',  # token认证
    )
}

# 声明日志对象
from fy_rabc.common.log_helper import log_helper

SYS_LOG = log_helper()
