# Generated by Django 3.2.6 on 2021-09-14 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50, verbose_name='公司代码')),
                ('short_name', models.CharField(max_length=50, verbose_name='公司简称')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司全称')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='公司地址')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='公司电话')),
                ('logo_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='logo地址')),
                ('core_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='核心价值观')),
                ('status', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='记录状态')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建日期')),
                ('updator', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人')),
                ('updatedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日期')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '公司信息管理',
                'verbose_name_plural': '公司信息管理',
                'db_table': 't_sys_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_type', models.CharField(max_length=20, verbose_name='参数主类型')),
                ('name', models.CharField(max_length=50, verbose_name='参数名称')),
                ('value_type', models.CharField(choices=[('str', '字符串'), ('dic', '字典'), ('arr', '数组')], default='str', max_length=20, verbose_name='参数值类型')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='参数值')),
                ('status', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='记录状态')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建日期')),
                ('updator', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人')),
                ('updatedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日期')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '参数配置管理',
                'verbose_name_plural': '参数配置管理',
                'db_table': 't_sys_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.CharField(max_length=50, unique=True, verbose_name='组织架构代码')),
                ('org_name', models.CharField(max_length=50, verbose_name='组织架构名称')),
                ('org_type', models.CharField(choices=[('C', '公司'), ('D', '部门'), ('G', '小组'), ('P', '岗位')], default='D', max_length=1, verbose_name='组织架构类型')),
                ('status', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='记录状态')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建日期')),
                ('updator', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人')),
                ('updatedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日期')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '组织架构管理',
                'verbose_name_plural': '组织架构管理',
                'db_table': 't_sys_org',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_code', models.CharField(max_length=50, unique=True, verbose_name='资源代码')),
                ('res_type', models.CharField(choices=[('M', '菜单'), ('A', '操作')], default='M', max_length=10, verbose_name='资源类型')),
                ('res_name', models.CharField(max_length=50, verbose_name='资源名称')),
                ('res_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='资源值')),
                ('status', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='记录状态')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建日期')),
                ('updator', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人')),
                ('updatedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日期')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '菜单资源管理',
                'verbose_name_plural': '菜单资源管理',
                'db_table': 't_sys_resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(max_length=50, unique=True, verbose_name='角色代码')),
                ('role_name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('status', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='记录状态')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建日期')),
                ('updator', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人')),
                ('updatedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日期')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '角色信息管理',
                'verbose_name_plural': '角色信息管理',
                'db_table': 't_sys_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleResModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_res_code', models.CharField(max_length=50, unique=True, verbose_name='角色资源代码')),
                ('status', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='记录状态')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建日期')),
                ('updator', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人')),
                ('updatedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日期')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '角色资源管理',
                'verbose_name_plural': '角色资源管理',
                'db_table': 't_sys_role_res',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=50, unique=True, verbose_name='用户代码')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户姓名')),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户昵称')),
                ('ico_img', models.CharField(blank=True, max_length=100, null=True, verbose_name='头像图片地址')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], default=1, null=True, verbose_name='性别')),
                ('id_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号码')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='E-Mail地址')),
                ('login_name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='登录名')),
                ('pwd', models.CharField(blank=True, default='123456', max_length=100, null=True, verbose_name='登录密码')),
                ('status', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='记录状态')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建日期')),
                ('updator', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人')),
                ('updatedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日期')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用户信息管理',
                'verbose_name_plural': '用户信息管理',
                'db_table': 't_sys_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role_code', models.CharField(max_length=50, unique=True, verbose_name='用户角色代码')),
                ('status', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='记录状态')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建日期')),
                ('updator', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人')),
                ('updatedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新日期')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用户角色管理',
                'verbose_name_plural': '用户角色管理',
                'db_table': 't_sys_user_role',
                'managed': False,
            },
        ),
    ]
